# Generated by Django 5.2.6 on 2025-09-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_remove_recommendation_score_and_more'),
        ('reviews', '0002_remove_review_content_review_comment_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
