# Generated by Django 5.2 on 2025-10-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_genre_remove_movie_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(default='https://via.placeholder.com/280x400?text=No+Poster'),
        ),
    ]
